import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import Sidebar from "./components/sidebar";

import { Poppins } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className="container px-60 mx-auto flex justify-between py-4 gap-10 ">
          <div className="w-4/5 ">{children}</div>
          <div className="w-1/5 ">
            <Sidebar />
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
